runners:
 AWS-runner:
  image: vitis-ai-14

jobs:   
 run-vitis-ai:
  runner: AWS-runner
  type:
   test: sw-emulation
  current_working_directory: /workspace/sign_language_mnist-master    
  steps:
   - run:
      name: Test
      command: |
       echo "start"
       ls -l /proc/$$/exe
       conda activate vitis-ai-tensorflow2
       pip install keras==2.6       
       sudo apt-get update;
       sudo apt-get install awscli -y;
       aws s3 cp s3://vitis-ai-bucket/sign_language_mnist-master.zip /workspace/
       aws s3 cp s3://vitis-ai-bucket/archive.zip /workspace/
       unzip /workspace/sign_language_mnist-master.zip -d /workspace/
       unzip /workspace/archive.zip -d /workspace/sign_language_mnist-master
       cd /workspace/sign_language_mnist-master
       ./run_sign_language_mnist.sh
       echo "Finished"       
       
workflows:
 vitis-ai-test:
  triggers:
   - manual  
   - push
  jobs:
   - run-vitis-ai
   
