runners:
 ai-runner:
  image: ip-192-168-98-98:5000/vitis-ai-14

jobs:   
 run-vitis-ai:
  runner: ai-runner
  type:
   test: sw-emulation
  current_working_directory: /workspace/sign_language_mnist
  input: 
   artifact: 
    - archive.zip
  output: 
   artifact: 
    - deploy
  steps:
   - run:
      name: Test
      command: |
       echo "start"
       ls -l /proc/$$/exe
       conda activate vitis-ai-tensorflow2
       pip install keras==2.6
       ls
       ./run_sign_language_mnist.sh
       echo "Finished"    
       
workflows:
 vitis-ai-test:
  triggers:
   - manual  
  jobs:
   - run-vitis-ai
